apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-1
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: ubuntu
      labels:
        app: backend
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          command: ["cat"]
          args: ["etc/*release*"]
          envFrom:
            - configMapRef:
                name: app-config1
          securityContext:
            runAsUser: 1000  # takes precedent over pod level context, must be integrer
            capabilities:  # which admin capabilities are getting added or dropped
              add: ["MAC_ADMIN"]
              drop: ["something else"]
          resources:
            requests:
              cpu: 500mi
              memory: 1 Gi
            limits:
              cpu: 1
              memory: 2 Gi
      serviceAccountName: <sa-name>
      automountServiceAccountToken: true # true/fals - true by default
      tolerations:  # requires the node(s) to be tainted  --> kubectl taint nodes <node-name> key=value:effect
        - key: "app"  # arbitrary
          operator: "Equal"  # condition
          value: "blue"  # arbitrary
          effect: "NoSchedule"   # PreferNoSchedule  NoExecute are other options



