apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-1
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: ubuntu
      labels:
        app: backend
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          command: ["cat"]
          args: ["etc/*release*"]
          envFrom:
            - configMapRef:
                name: app-config1
          securityContext:
            runAsUser: bar  # takes precedent over pod level context
            capabilities:  # which admin capabilities are getting added or dropped
              add: ["MAC_ADMIN"]
              drop: ["something else"]
          requirements:
            requests:
              cpu: 500mi
              memory: 1 Gi
            resources: # stadard resource setting
              requests:
                cpu:
                memory:
              limits:
                cpu:
                memory:
      serviceAccountName: <sa-name>
      automountServiceAccountToken: # true/fals - true by default
      securityContext:
        runAsUser: foo
        capabilities:
          add: ["capability"]
          drop: ["capability"]

      tolerations:  # requires the node(s) to be tainted  --> kubectl taint nodes <node-name> key=value:effect
        - key: "app"  # arbitrary
          operator: "Equal"  # condition
          value: "blue"  # arbitrary
          effect: "NoSchedule"   # PreferNoSchedule  NoExecute are other options



