apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: dev
spec:
  limits:
    - default:
        cpu: 500m
        memory: 1 Gi
      defaultRequest:
        cpu: 500m
        memory: 1 Gi
      max:
        cpu: 2
        memory: 3 Gi
      min:
        cpu: 100m
        memory: 0.5 Gi
      type: Container
