apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webapp-pod
  name: webapp-pod
spec:
  ports:
  - name: 80-80
    nodePort: 30005
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp-pod
  type: NodePort
status:
  loadBalancer: {}
