apiVersion: v1
kind: Secret
metadata:
  name: secret-1
  annotations:
    kubernetes.io/serviceaccount.name: <sa name> # if using non-default sa and token
data:
  key1: foo # this will be base64 encrypted echno -n "secret" | base64
  key2: bar # decrypted echo "encypted text" | base64 --decode
