apiVersion: v1
kind: Service
metadata:
  labels:
    app: foo
  name: webapp-pod
spec:
  ports:
  - name: 80-80
    nodePort: 30005
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: foo
  type: NodePort
status:
  loadBalancer: {}
