apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  selector:
    name: voting-app-pod
    app: demo-voting-app
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005