apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp
  labels:
    app: mydb
spec:
  containers:
    - name: mydb
      image: mysql
      ports:
        - containerPort: 3306
      livenessProbe:
        exec:
          command:
            - cat
            - /etc/*release*
        initialDelaySeconds: 20
        periodSeconds: 5
        failureThreshold: 5