apiVersion: v1
kind: Pod
metadata:
  name: http-readiness
  labels:
    app: myapp
spec:
  containers:
    - name: simple-webapp
      image: simple-webapp
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /api/ready
          port: 8080
          httpHeaders:
            - name: Custom-header
              value: Awesomet
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 4