apiVersion: v1
kind: Pod
metadata:
  name: tcp-readiness
  labels:
    app: myapp
spec:
  containers:
    - name: db
      image: mysql
      ports:
        - containerPort: 3306
      readinessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 20
        periodSeconds: 5
        failureThreshold: 5