apiVersion: v1
kind: Pod
metadata:
  name: readiness-command
  labels:
    app: myapp
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      readinessProbe:
        exec:
          command:
            - cat
            - etc/*release*
        initialDelaySeconds: 30
        periodSeconds: 5
        failureThreshold: 8  # default = 3