apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  labels:
    app: myapp2
    type: frontend
spec:
  selector:
    matchLabels:
      type: frontend
  replicas: 6
  template:
    metadata:
      name: nginx2
      labels:
        app: myapp2
        type: frontend
    spec:
      containers:
        - name: apache-container
          image: httpd
          ports:
            - containerPort: 80
