apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployemnt1
  labels:
    app: myapp1
    type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      name: myginx-pod
      labels:
        type: frontend
        app: nginx1
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
