apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend-app
  annotations:
    nginx.kubernetes.io/use-reg-ex: "true"
spec:
  tls: # this is how https gets set up
    - hosts:
      - example.com
      secretName: example-secret
  defaultBackend:
    service:
      name: default-backend
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /foo
        pathType: ImplementationSpecific
        backend:
          service:
            name: foo-deployment-service
            port:
              number: 80
      - path: /bar
        pathType: Prefix
        backend:
          service:
            name: bar-deployment-service
            port:
              number: 80