apiVersion: v1
kind: Secret
metadata:
  name: nginx-ingress-serviceaccount
  annotations:
    kubernetes.io/serviceaccount.name: nginx-ingress
data:
  key1: foo
  key2: bar
---
# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-role
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-rolebinding
subjects:
- kind: ServiceAccount
  name: nginx-ingress-serviceaccount
roleRef:
  kind: Role
  name: example-role
  apiGroup: rbac.authorization.k8s.io/v1
---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-clusterrole
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: example-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: nginx-ingress-serviceaccount
roleRef:
  kind: ClusterRole
  name: example-clusterrole
  apiGroup: rbac.authorization.k8s.io/v1
