apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  labels:
    kind: sidecar
spec:
  containers:
    - name: web-server
      image: web-server
      ports:
        - containerPort: 80
    - name: log-agent
      image: log-agent
