apiVersion: v1
kind: LimitRange # applicable at the namespace level
metadata:
  name: my-limit-range
spec:
  limits:
    - default:
        cpu:
        memory:
      defaultRequest:
        cpu:
        memory:
      max:
        cpu:
        memory:
      min:
        cpu:
        memory:
      type: Container
