apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    kind: frontend
spec:
  selector:
    matchLabels:
      type: frontend
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx