apiVersion: v1
kind: Service
metadata:
 name: redis
 labels:
  app: demo-voting-app
  name: redis-service
spec:
  selector:
    name: redis-pod
    app: demo-voting-app
  ports:
    - targetPort: 6379
      port: 6379
  type: ClusterIP