apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  selector:
    name: result-app-pod
    app: demo-voting-app
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30004