apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-canary
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-container
      labels:
        version: v2
        app: front-end
    spec:
      containers:
        - name: myapp
          image: myapp:v2
  replicas: 1
  selector:
    matchLabels:
      app: front-end
