apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-canary
  labels:
    version: v2
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v2
    spec:
      containers:
        - name: myapp
          image: myapp:v2
  replicas: 1
  selector:
    matchLabels:
      version: v2
