apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-administrator
rules:
- apiGroups: [""]
  resources: ["nodes"]  # note: you can add namespaced resources (e.g., Deploymen) and it will enable across all ns in cluster
  verbs: ["list", "get", "create", "delete"]