apiVersion: v1
kind: Service
metadata:
 name: my-lb
spec:
  type: LoadBalancer
  ports:
  - port: 89
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  - port: 5000
    targetPort: 5000
    name: backend
