apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: worker-deployment
    app: demo-voting-app
    type: backend
spec:
  selector:
    matchLabels:
      name: worker-pod
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      name: worker-app
      labels:
        name: worker-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_worker:v1