apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: google-storage # this is the StorageClass object's name
  resources:
    requests:
      storage: 500Mi
