apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
  - name: alpine
    image: alpine
    command: [ "/bin/sh" ]
    args:
    - "-c"
    - "shuf -i 0-100 -n 1 >> /opt/number.txt"
    volumeMounts:
    - mountPath: /opt
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: myclaim
