apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    name: result-deployment
    app: demo-voting-app
    type: frontend
spec:
  selector:
    matchLabels:
      name: result-app
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      name: result-pod
      labels:
        app: demo-voting-app
        name: result-pod
    spec:
      containers:
        - name: result-pod
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80

