apiVersion: v1
kind: Service
metadata:
  name: myapp-clusterip
  labels:
    kind: clusterip
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myapp2
    type: frontend