apiVersion: v1
kind: Service
metadata:
  name: practice-load-balancer
  labels:
    type: loadbalancer
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30011
  selector:
    app: myapp3
    type: backend